name: Test codebuild from Github Actions
on: workflow_dispatch
jobs:
    get_context:
      runs-on: ubuntu-latest
      steps:
        - run: echo ${{ github.sha }}
    terraform-dev:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # This is required for requesting the JWT
            contents: read  # This is required for actions/checkout
        steps:
            - uses: aws-actions/configure-aws-credentials@v2
              with:
                role-to-assume: arn:aws:iam::027359714311:role/gh-iam-role
                aws-region: eu-central-1
            - uses: aws-actions/aws-codebuild-run-build@v1.0.12
              with:
                project-name: test-ga-build
                disable-source-override: true
                env-vars-for-codebuild: |
                    TF_COMMAND,
                    TF_OPTIONS,
                    ENVIRONMENT,
                    SHA
              env: 
                    TF_COMMAND: plan
                    TF_OPTIONS: -var-file=./environments/dev/params.tfvars
                    ENVIRONMENT: dev
                    SHA: "${{ github.sha }}"
    terraform-prod:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # This is required for requesting the JWT
            contents: read  # This is required for actions/checkout
        steps:
            - uses: aws-actions/configure-aws-credentials@v2
              with:
                role-to-assume: arn:aws:iam::027359714311:role/gh-iam-role
                aws-region: eu-central-1
            - uses: aws-actions/aws-codebuild-run-build@v1.0.12
              with:
                project-name: test-ga-build
                disable-source-override: true
                env-vars-for-codebuild: |
                    TF_COMMAND,
                    TF_OPTIONS,
                    ENVIRONMENT,
                    SHA
              env: 
                    TF_COMMAND: plan
                    TF_OPTIONS: -var-file=./environments/prod/params.tfvars
                    ENVIRONMENT: prod
                    SHA: "${{ github.sha }}"