name: Test codebuild from Github Actions
on: workflow_dispatch
jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
            - uses: aws-actions/configure-aws-credentials@v2
              with:
                role-to-assume: arn:aws:iam::027359714311:role/gh-iam-role
                aws-region: eu-central-1
            -  uses: aws-actions/aws-codebuild-run-build@v1
               with:
                project-name: test-ga-build
                env-vars-for-codebuild: |
                    TF_COMMAND,
                    TF_OPTIONS,
                    ENVIRONMENT
               env:
                    TF_COMMAND: plan
                    TF_OPTIONS: -var-file=./environments/dev/params.tfvars -backend-config=./environments/dev/s3backend.hcl
                    ENVIRONMENT: dev