name: Test paths
on:
    pull_request:
        types:
            - opened
            - synchronize
            - closed
        paths:
            - 'terraform/**'

jobs:
    main-job:
        runs-on: ubuntu-latest
        steps:
            - name: print context
              run: echo "${{ toJson(github) }}"