name: Test paths
on:
    pull_request:
        types:
            - opened
            - synchronize
            - closed

jobs:
    main-job:
        runs-on: ubuntu-latest
        steps:
            - name: print context
              run: echo "${{ github }}"
