name: Test PR test
on: 
  pull_request:
    branches:
      - dev
      - uat
      - main
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: print github context
        run: |
          echo "${{ toJson(github) }}"
      - name: print event context
        run: |
          echo ${{ github.event.pull_request.base.ref }}
          
