name: Test self hosted runner
on:
    workflow_dispatch:

jobs:
    run-docker:
        runs-on: test-runner
        steps:
            - name: run docker
              run: docker run -d nginx:latest
