name: Access AWS
on: 
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  access_aws:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    name: Assume role
    steps:
      - name: assume role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::027359714311:role/gh-iam-role
          aws-region: us-east-1
          role-session-name: MySessionName
      - name: get the secret value
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            arn:aws:secretsmanager:eu-west-1:027359714311:secret:/test/secret-AkscEJ


      