name: Access AWS
on: 
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  access_aws:
    runs-on: ubuntu-latest
    name: Assume role
    steps:
      - name: assume role
        env:
          ACTIONS_STEP_DEBUG: true
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::027359714311:role/gh-iam-role
          aws-region: us-east-1
          role-session-name: MySessionName


      