name: Access AWS
on: 
  push:
    branches:
      - main
jobs:
  access_aws:
    name: Assume role
    steps:
      - name: assume role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::027359714311:role/gh-iam-role
          aws-region: us-east-1


      